name: astronomy_picture
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  mockito: ^5.4.0
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.3.0
  video_player: ^2.6.1
  youtube_player_flutter: ^8.1.2
  vimeo_video_player: ^0.0.9
  gallery_saver: ^2.3.2
  share_plus: ^6.3.4
  shared_preferences: ^2.1.0
  timezone: ^0.9.2
  syncfusion_flutter_datepicker: ^21.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3


flutter:

  uses-material-design: true